{
 "title": "GolangProcess",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MemoryUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPUUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Go Thread",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}