global:
  # How frequently to scrape targets by default.
  scrape_interval: 10s

  # How long until a scrape request times out.
  scrape_timeout: 10s

rule_files:
- "rules/alerts.rules.yml"
      
scrape_configs:
  - job_name: 'prom-scrape'
    static_configs:
    - targets:
      - 'localhost:9090'
  - job_name: 'traefik-scrape'
    static_configs:
    - targets:
      - 'traefik:8082'
  - job_name: 'cockroachdb'
    metrics_path: '/_status/vars'
    scheme: 'http'
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: 
        - 'db_cockroach_1:8080'
  - job_name: 'redis_exporter'
    static_configs:
      - targets: 
        - 'redis-exporter:9121'